### ISSUE TITLE
写入变量失败

### ISSUE THREAD

**Issue by Ry4nnnnn** [IanChen0713/Hackintosh-HP-PAVILION-GAMING-LAPTOP-15-dk0xxx#1]
您好，我今天在改完之后，想要保存，出现了这个提示：write variable failed: 0x00000008
请问如何解决

**Comment by HaynesChennn** [comment]
> 您好，我今天在改完之后，想要保存，出现了这个提示：write variable failed: 0x00000008
> 
> 请问如何解决

应该是新版本的bios写了保护 参考[issue](https://github.com/JamesAmiTw/ru-uefi/issues/6)
可以尝试降级bios 可能会有用 ：）

**Comment by Ry4nnnnn** [comment]
> > 您好，我今天在改完之后，想要保存，出现了这个提示：write variable failed: 0x00000008
> > 请问如何解决
> 
> 应该是新版本的bios写了保护 参考[issue](https://github.com/JamesAmiTw/ru-uefi/issues/6) 可以尝试降级bios 可能会有用 ：）

有没有具体的降级办法呢，网上没有搜到

**Comment by Ry4nnnnn** [comment]
> > 您好，我今天在改完之后，想要保存，出现了这个提示：write variable failed: 0x00000008
> > 请问如何解决
> 
> 应该是新版本的bios写了保护 参考[issue](https://github.com/JamesAmiTw/ru-uefi/issues/6) 可以尝试降级bios 可能会有用 ：）

有没有具体的降级办法呢，网上没有搜到

**Comment by HaynesChennn** [comment]
08错误是写保护 [issue](https://github.com/JamesAmiTw/ru-uefi/issues/7)

**Comment by Ry4nnnnn** [comment]
> 08错误是写保护 [issue](https://github.com/JamesAmiTw/ru-uefi/issues/7)

既然旧版本的bios可以修改的话，那请问您有什么办法可以降级bios的吗，我想安装黑苹果，但是他卡在了eb，或者还有其他解决卡eb的办法没有。

**Comment by Ry4nnnnn** [comment]
> 08错误是写保护 [issue](https://github.com/JamesAmiTw/ru-uefi/issues/7)

既然旧版本的bios可以修改的话，那请问您有什么办法可以降级bios的吗，我想安装黑苹果，但是他卡在了eb，或者还有其他解决卡eb的办法没有。

**Comment by HaynesChennn** [comment]
> > > 您好，我今天在改完之后，想要保存，出现了这个提示：write variable failed: 0x00000008
> 
> > > 请问如何解决
> 
> > 
> 
> > 应该是新版本的bios写了保护 参考[issue](https://github.com/JamesAmiTw/ru-uefi/issues/6) 可以尝试降级bios 可能会有用 ：）
> 
> 
> 
> 有没有具体的降级办法呢，网上没有搜到

我没有降级过 这个视频可能有用:)
[video](https://youtu.be/yxm1BuW92hY?si=KwNzOcv3i_7Edmw0)
